# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# https://game-store-react.azurewebsites.net/
# https://game-store-react2.azurewebsites.net/
# https://jojozhuang.github.io/game-store-react/

name: Build and Deploy

on:
  push:
    branches:
      - add-e2e-test-with-cypress
  workflow_dispatch:

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build:azure

      - name: Upload artifact for test/deploy jobs
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: ./dist # package all files in dist/browser and name the artifact "react-app"

  test:
    name: Run Unit and E2E Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:headless

      - name: Run e2e tests
        run: npm run e2e:headless

  deploy-azure-game-store:
    name: Deploy to Azure game-1
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app # download the artifact and extract to the current working directory

      - name: Deploy to Azure game-store-react
        id: deploy-to-game1
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'game-store-react'
          slot-name: 'Production'
          package: . # deploy with all files in the current working directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_798C823CA40D493EA695D1EC0FF5D56F }}
          clean: true

  deploy-azure-game-store3:
    name: Deploy to Azure game-2
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app # download the artifact and extract to the current working directory

      - name: Deploy to Azure game-store-react2
        id: deploy-to-game2
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'game-store-react2'
          slot-name: 'Production'
          package: . # deploy with all files in the current working directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1DF29CD77BC64FD2AD124FBEA61BC1C2 }}
          clean: true

  deploy-github-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build:pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true

